language: node_js
node_js:
  - '12.13.1'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - |
    # Prune & rebuild node_modules
    if [[ -d node_modules ]]; then
      yarn install
      yarn prebuild
    fi
script:
  - |
    # Run test script
    yarn test
before_deploy: "echo 'ready to deploy?'"
deploy:
  provider: heroku
  api_key:
    secure: '0889a92b-ab29-4aa7-adaf-3274aef93f1a'
  app:
    master: test-ci-88
  on:
    condition: node
