version: 2.1

commands:
  test:
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:cov
  build:
    steps:
      - checkout
      - run: yarn prebuild
      - run: yarn build
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

executors:
  test-ci-executor:
    docker:
      - image: circleci/node:12.13.1

jobs:
  test:
    working_directory: ~/test-ci
    executor: test-ci-executor
    steps:
      - test
  build:
    working_directory: ~/test-ci
    executor: test-ci-executor
    steps:
      - build
  deploy:
    working_directory: ~/test-ci
    executor: test-ci-executor
    steps:
      - deploy

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - circleci
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - circleci
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci
